/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import static Frontend.ViewProducts.e;
import Backend.EmployeeRole;
import Backend.Product;
import javax.swing.JFrame;
import javax.swing.text.TableView;

/**
 *
 * @author ADMIN
 */
public class Employeerole extends javax.swing.JFrame implements Node{
      EmployeeRole x=new EmployeeRole();
      
       private Node parent;
    
    public Employeerole() {
        initComponents();
        configureWindow();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProduct = new javax.swing.JButton();
        viewProduct = new javax.swing.JButton();
        purchaseProduct = new javax.swing.JButton();
        viewPP = new javax.swing.JButton();
        returnProduct = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addProduct.setBackground(new java.awt.Color(0, 0, 0));
        addProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addProduct.setForeground(new java.awt.Color(255, 255, 255));
        addProduct.setText("Add Product");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        viewProduct.setBackground(new java.awt.Color(0, 0, 0));
        viewProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewProduct.setForeground(new java.awt.Color(255, 255, 255));
        viewProduct.setText("View Products ");
        viewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductActionPerformed(evt);
            }
        });

        purchaseProduct.setBackground(new java.awt.Color(0, 0, 0));
        purchaseProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        purchaseProduct.setForeground(new java.awt.Color(255, 255, 255));
        purchaseProduct.setText("Purchase Product");
        purchaseProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseProductActionPerformed(evt);
            }
        });

        viewPP.setBackground(new java.awt.Color(0, 0, 0));
        viewPP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewPP.setForeground(new java.awt.Color(255, 255, 255));
        viewPP.setText("View Purchase Products");
        viewPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPPActionPerformed(evt);
            }
        });

        returnProduct.setBackground(new java.awt.Color(0, 0, 0));
        returnProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnProduct.setForeground(new java.awt.Color(255, 255, 255));
        returnProduct.setText("Return Product");
        returnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnProductActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPP, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addProduct, logout, purchaseProduct, returnProduct, viewPP, viewProduct});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(purchaseProduct)
                .addGap(31, 31, 31)
                .addComponent(viewPP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(returnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addProduct, logout, purchaseProduct, returnProduct, viewPP, viewProduct});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
      private void configureWindow() {
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); // Prevent closing by "X" button
        //setSize(400, 300); // Set the window size
        setLocationRelativeTo(null); // Center the window on the screen
        setVisible(true);
    }

    private void viewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductActionPerformed
        
        this.setVisible(false);
        ViewProducts vp=new ViewProducts(x);
        vp.setVisible(true);
        vp.setParentNode(this);
        
    }//GEN-LAST:event_viewProductActionPerformed

    private void viewPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPPActionPerformed
        this.setVisible(false);
        ViewPurchaseProducts pp=new ViewPurchaseProducts(x);
        pp.setVisible(true);
        pp.setParentNode(this);
        
    }//GEN-LAST:event_viewPPActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
      this.setVisible(false);
      AddProduct a =new AddProduct(x);
      a.setVisible(true);
      a.setParentNode(this);
    
       
    }//GEN-LAST:event_addProductActionPerformed

    private void purchaseProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseProductActionPerformed
       this.dispose();
        PurchaseProduct p=new PurchaseProduct(x);
       p.setVisible(true );
      p.setParentNode(this);
    }//GEN-LAST:event_purchaseProductActionPerformed

    private void returnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnProductActionPerformed
       this.dispose();
       ReturnProduct r=new ReturnProduct(x);
       r.setVisible(true);
       r.setParentNode(this);
             
    }//GEN-LAST:event_returnProductActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        x.logout();
        this.setVisible(false);
      new InventorySystem().setVisible(true);
        
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employeerole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employeerole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employeerole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employeerole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employeerole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JButton logout;
    private javax.swing.JButton purchaseProduct;
    private javax.swing.JButton returnProduct;
    private javax.swing.JButton viewPP;
    private javax.swing.JButton viewProduct;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
        return parent; 
    }

    @Override
    public void setParentNode(Node node) {
        this.parent=node;}
}
